// AUTOGENERATED CONTENT
export const backgroundColor = 'var(--background-color)';
export const textColorPrimary = 'var(--text-color-primary)';
export const primaryTaskanyLogoColor = 'var(--primary-taskany-logo-color)';
export const secondaryTaskanyLogoColor = 'var(--secondary-taskany-logo-color)';
export const success = 'var(--success)';
