// AUTOGENERATED CONTENT
export const backgroundColor = 'var(--background-color)';
export const textColorPrimary = 'var(--text-color-primary)';
export const cardBorderColor = 'var(--card-border-color)';
export const formInputBackgroundColor = 'var(--form-input-background-color)';
export const toastTextColor = 'var(--toast-text-color)';
export const toastBackgroundColor = 'var(--toast-background-color)';
export const primaryTaskanyLogoColor = 'var(--primary-taskany-logo-color)';
export const secondaryTaskanyLogoColor = 'var(--secondary-taskany-logo-color)';
export const success = 'var(--success)';
