// AUTOGENERATED CONTENT
import { createGlobalStyle } from 'styled-components';

export default createGlobalStyle`
    :root {
        --font-display: -apple-system, BlinkMacSystemFont, "Helvetica Neue", "Segoe UI", "Fira Sans", Roboto, Ubuntu, "Droid Sans", "Arial", sans-serif;
        --gap-xs: 0.25rem;
        --gap-s: 0.5rem;
        --gap-sm: 0.75rem;
        --gap-m: 1rem;
        --gap-l: 2rem;
        --gap-xl: 4rem;
        --brand-color: #17b978;
        --color-primary: #108858;
        --color-primary-accent: #17b978;
        --text-color-primary: #fff;
        --text-color: hsl(0, 0%, 15%);
        --background-color: #f6f9fc;
        --gray0: hsl(1, 0%, 50%);
        --gray1: hsl(1, 0%, 98%);
        --gray2: hsl(1, 0%, 96%);
        --gray3: hsl(1, 0%, 94%);
        --gray4: hsl(1, 0%, 90%);
        --gray5: hsl(1, 0%, 86%);
        --gray6: hsl(1, 0%, 81%);
        --gray7: hsl(1, 0%, 74%);
        --gray8: hsl(1, 0%, 66%);
        --gray9: hsl(1, 0%, 55%);
        --gray10: hsl(1, 0%, 39%);
        --warn0: hsl(30, 100%, 50%);
        --warn1: hsl(30, 100%, 98%);
        --warn2: hsl(30, 100%, 96%);
        --warn3: hsl(30, 100%, 94%);
        --warn4: hsl(30, 100%, 90%);
        --warn5: hsl(30, 100%, 86%);
        --warn6: hsl(30, 100%, 81%);
        --warn7: hsl(30, 100%, 74%);
        --warn8: hsl(30, 100%, 66%);
        --warn9: hsl(30, 100%, 55%);
        --warn10: hsl(30, 100%, 39%);
        --danger0: hsl(360, 100%, 50%);
        --danger1: hsl(360, 100%, 98%);
        --danger2: hsl(360, 100%, 96%);
        --danger3: hsl(360, 100%, 94%);
        --danger4: hsl(360, 100%, 90%);
        --danger5: hsl(360, 100%, 86%);
        --danger6: hsl(360, 100%, 81%);
        --danger7: hsl(360, 100%, 74%);
        --danger8: hsl(360, 100%, 66%);
        --danger9: hsl(360, 100%, 55%);
        --danger10: hsl(360, 100%, 39%);
        --form-input-background-color: rgba(0, 0, 0, .03);
        --form-input-error-color: #e00;
        --popup-danger-background-color: #e00;
        --popup-warning-background-color: #f5a623;
        --link-text-color: #00C2FF;
    }
`;
