// AUTOGENERATED CONTENT
import { createGlobalStyle } from 'styled-components';

export default createGlobalStyle`
    :root {
        --background-color: #fff;
        --text-color-primary: #000;
        --primary-taskany-logo-color: #000;
        --secondary-taskany-logo-color: #17b978;
        --success: #149561;
    }
`;
